kind: pipeline
name: sisyphus

steps:
- name: test-shellcheck
  image: koalaman/shellcheck-alpine:latest
  commands:
  - apk update && apk add bash
  - bash -c 'shellcheck sisyphus'

- name: test-sisyphus-alpine
  image: alpine
  commands:
  - apk update && apk add bash
  - ./sisyphus
  
- name: test-sisyphus-ubuntu
  image: ubuntu
  commands:
  - ./sisyphus

- name: test-sisyphus-centos
  image: centos
  commands:
  - ./sisyphus
