kind: pipeline
name: greeting

steps:
- test-shellcheck:
  image: koalaman/shellcheck-alpine:latest
  commands:
  - apk update && apk add bash
  - bash -c 'shellcheck sisyphus'

- name: en
  image: alpine
  commands:
  - echo hello
  - echo world

- name: es
  image: alpine
  commands:
  - echo hola
  - echo mundo

- name: fr
  image: alpine
  commands:
  - echo bonjour
  - echo monde
