kind: pipeline
name: sisyphus

steps:
- name: test-shellcheck
  image: koalaman/shellcheck-alpine:latest
  commands:
  - apk update && apk add bash
  - bash -c 'shellcheck sisyphus'

- name: test-sisyphus-alpine
  image: alpine
  commands:
  - apk update && apk add bash
  - ./sisyphus
  - ./sisyphus -k write
  depends_on: [test-shellcheck]
  
- name: test-sisyphus-ubuntu
  image: ubuntu
  commands:
  - ./sisyphus
  - ./sisyphus -k read
  depends_on: [test-shellcheck]

- name: test-sisyphus-centos
  image: centos
  commands:
  - ./sisyphus
  - ./sisyphus -k eat
  depends_on: [test-shellcheck]

- name: test-sisyphus-debian
  image: debian
  commands:
  - ./sisyphus
  - ./sisyphus -k drink
  depends_on: [test-shellcheck]

- name: test-sisyphus-fedora
  image: fedora
  commands:
  - ./sisyphus
  - ./sisyphus -k take
  depends_on: [test-shellcheck]

- name: test-sisyphus-opensuse
  image: opensuse/tumbleweed
  commands:
  - ./sisyphus
  - ./sisyphus -k go
  depends_on: [test-shellcheck]
