#!/bin/bash
#
# sisphyus - tools for the never ending task
#
# there's lots of ways to pick a random line from a file

SHUF="shuf -n 2"

case "$OSTYPE" in
        darwin*)        SHUF="gshuf -n 2"
esac

case "$1" in
        -k)             SHUF="grep -i $2"
esac



$SHUF <<EOSHUF
Add a line to this file with a PR to https://github.com/vielmetti/sisyphus.
Boil the kettle.
Carry something (up/down) the stairs.
Change the frequency.
Charge the computer.
Charge the phone.
Clean up five things.
Clear a space on your desk.
Close a drawer / open a drawer.
Close an issue in Github.
Close the computer.
Cover your mouth when you cough.
Did you take your meds?
Drink a glass of water.
Eat a snack.
Find a pen.
Floss one tooth.
Get up and stretch.
Get up and take a walk.
Go to bed.
Have a piece of fruit.
Improve your posture.
How late is it?
Make a cup of tea.
Make a sandwich.
Make the bed.
Move the laundry around.
(Open/close) the curtains.
Open a book / put away a book.
Open an issue in Github.
Open one envelope.
Open up Facebook, read, sigh, close Facebook.
Open up Twitter, read, sigh, close Twitter.
Pet the cat.
Read the oldest message in the inbox.
Refill the water bottle.
Shine the sink.
Sort the todo list.
Sudo make me a sandwich.
Take a shower.
(Take out/put back) a rolodex card.
Take out the trash.
Take your meds.
Take out the compost.
Tidy.
Tidy up the couch.
Tune your radio.
Turn (on/off) one light.
Turn (on/off) the fan.
Turn the radio (on/off).
Wash your hands.
Wear a mask when you are out.
What time is it?
What is for dinner?
Where are your glasses?
Where is the car parked?
Write one rolodex card.
Write on a piece of paper.
Write one sentence.
EOSHUF
