#!/bin/bash
#
# sisphyus - tools for the never ending task
#
# there's lots of ways to pick a random line from a file

SHUFCOUNT=2

case "$1" in 
        -n)             SHUFCOUNT="$2" ;;
esac

awk -v k=$SHUFCOUNT <<EOSHUF \
  'BEGIN {srand(systime() + PROCINFO["pid"])} \
  { s = NR <= k ? NR : int(rand() * NR);  if (s < k) R[s] = $0  } \
  END {for (i in R) print R[i]}'
Add a line to this file with a PR to https://github.com/vielmetti/sisyphus.
All you have to do is ask.
Bird by bird.
Boil the kettle.
Carry something (up/down) the stairs.
Change the frequency.
Charge the computer.
Charge the phone.
Clean up five things.
Clear a space on your desk.
Close a drawer / open a drawer.
Close an issue in Github.
Close the computer.
Cover your mouth when you cough.
Did you take your meds?
Do the laundry.
Drink a glass of water.
Eat a snack.
Find a pen.
Floss one tooth.
Fortune favors the (brave, lucky, cookie).
Get up and stretch.
Get up and take a walk.
Go to bed.
Have a piece of fruit.
Improve your posture.
Is it busted?
Is the back door open?
Is the laundry basket full?
How late is it?
(Load/unload) the dishwasher.
(Load/unload) the laundry.
Make a cup of tea.
Make a sandwich.
Make the bed.
Move the laundry around.
(Open/close) the curtains.
Open a book / put away a book.
Open an issue in Github.
Open one envelope.
Open up Facebook, read, sigh, close Facebook.
Open up Twitter, read, sigh, close Twitter.
Pet the cat.
Read one sentence from a book.
Read the oldest message in the inbox.
Refill the water bottle.
Shine the sink.
Sort the todo list.
Stop long enough to notice what's around you.
Sudo make me a sandwich.
Sweep the floor.
Take a shower.
(Take out/put back) a rolodex card.
Take out the trash.
Take a trash bag (up to/down from) the attic.
Take your meds.
Take out the compost.
Tidy.
Tidy up the couch.
Tidy up the laundry.
Tune your radio.
Turn (on/off) one light.
Turn (on/off) the fan.
Turn the radio (on/off).
Wash the dishes.
Wash your hands.
Wear a mask when you are out.
What time is it?
What is for lunch?
What is for dinner?
Where are your glasses?
Where is the car parked?
Write one rolodex card.
Write on a piece of paper.
Write one sentence.
Writing is like talking to the page.
EOSHUF
